### ISSUE TITLE
[ERROR] "No such file or directory" while installing on Ubuntu 22.04

### ISSUE THREAD

**Issue by paladini** [andersonbosa/moshell.sh#1]
## Context

I've tried to install moshell.sh on Ubuntu 22.04 and when I tried to run `source ~/.moshell.sh/moshell.sh/moshell.sh
` command to test moshell.sh, I got the following errors:

```shell
paladini@fernando-ubuntu:~$ source ~/.moshell.sh/moshell.sh/moshell.sh 
bash: /home/paladini/lib/index.sh: No such file or directory
bash: /home/paladini/custom/index.sh: No such file or directory
``` 

## How to Reproduce

I just followed your instructions from the README and could not proceed in the second step because the errors above. 

I didn't tried to add the line `source ~/.moshell.sh/moshell.sh/moshell.sh` into my .bashrc or whatever, but run it directly in the Terminal (because I want to test before putting it in my dotfiles.

**Comment by andersonbosa** [comment]
I did some tests and I suspect it's a compatibility issue with the `basedir` function. The function works fine in ZSH but not in BASH. I think we can fix resolving this.

---
> `//core/index.sh` should be `/home/username/.moshell.sh/moshell.sh/core/index.sh`
> ![image](https://github.com/andersonbosa/moshell.sh/assets/8931900/4e31b4e4-0dc0-4b67-bdee-fdf0c31d53fd)

> [tmux-history-10-1-1-20230816T084121.log.txt](https://github.com/andersonbosa/moshell.sh/files/12358946/tmux-history-10-1-1-20230816T084121.log.txt)

**Comment by andersonbosa** [comment]
https://github.com/andersonbosa/moshell.sh/pull/2

**Comment by andersonbosa** [comment]
@paladini can you try our new version? Use the installation script https://github.com/andersonbosa/moshell.sh#install.

May need hotfix to `_moshell::print` but it should works fine ;D 

![image](https://github.com/andersonbosa/moshell.sh/assets/8931900/4fa825f1-f51f-46b1-b1a9-09603262972d)

---

I'll wait for your OK to close the Issue.

**Comment by paladini** [comment]
Okay, @andersonbosa , I will try it. Thanks for fixing it!
